### ISSUE TITLE
Add Licence File

### ISSUE THREAD

**Issue by hasssan** [fahmifan/bank-statement-parser-id#1]
Hi, 
First, thank you for the library.
Please include a license file in the project so it clearly states under which the code is licensed.

**Comment by fahmifan** [comment]
Hi @hasssan thanks for raising the issue, added the license file already, it's MIT license

https://github.com/fahmifan/bank-statement-parser-id/pull/2

**Comment by fahmifan** [comment]
I'm closing this issue then, thanks!
